<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Images\InfiniTI PRO - Icone Desktop.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Banner.png" />
    <None Remove="chat_icon.png" />
    <None Remove="Images\avatar.png" />
    <None Remove="Images\documento.png" />
    <None Remove="Images\enviar.png" />
    <None Remove="Images\foto.png" />
    <None Remove="Images\generico.png" />
    <None Remove="logout_icon.png" />
    <None Remove="logout_icon2.png" />
    <None Remove="ticket_icon.png" />
    <None Remove="ticket_icon2.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\InfiniTI PRO - Icone Desktop.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\avatar.png" />
    <Resource Include="Images\Banner.png" />
    <Resource Include="Images\chat_icon.png" />
    <Resource Include="Images\documento.png" />
    <Resource Include="Images\enviar.png" />
    <Resource Include="Images\foto.png" />
    <Resource Include="Images\generico.png" />
    <Resource Include="Images\logout_icon.png" />
    <Resource Include="Images\logout_icon2.png" />
    <Resource Include="Images\ticket_icon.png" />
    <Resource Include="Images\ticket_icon2.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="AnexosSistema\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="AnexosSistema\foto_tela.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="AnexosSistema\log_performance.pdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="AnexosSistema\relatorio_erro.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
